### ISSUE TITLE
SSL Certs on chef.altermundi.net

### ISSUE THREAD

**Issue by nicopace** [libremesh/alterchef#6]
## Expected behaviour

To have a verified SSL cert

## Actual behaviour

It delivers a self-singed cert.

## Steps to reproduce the behaviour

just go to https://chef.altermundi.net

**Comment by PabloCastellano** [comment]
I get a certificate signed by a known CA (StartCom Class 2 Primary Intermediate Server CA). Is it fixed?

**Comment by nicopace** [comment]
Might be... but we better migrate to letsencrypt... i'm getting on it now

**Comment by nicopace** [comment]
I added LetsEncrypt certificate and auto updater.
